### ISSUE TITLE
[Bug]: Build with included module fails even if "checkoutEndpoint" is provided in the config (@adyen/api-library)

### ISSUE THREAD

**Issue by bokjo** [Baroshem/nuxt-adyen-module#20]
### Expected Behavior

Hello @Baroshem, 

Thanks for the module, really helped me to test few payments with Ayden after some struggle and errors along the way...
Will create separate issues for all the findings.

After installing and configuring the module should be able to build and run my project

### Actual Behavior

Hello @Baroshem, 

Thanks for the module, really helped me to test few payments with Ayden after some struggle and errors along the way...
Will create separate issues for all the findings.

```sh
yarn build =>

 FATAL  Please provide your unique live url prefix on the setEnvironment() call on the Client or provide checkoutEndpoint in your config object.                                                                                                  23:04:58

  at Config.get checkoutEndpoint [as checkoutEndpoint] (node_modules/@adyen/api-library/lib/src/config.js:54:13)
  at new Payments (node_modules/@adyen/api-library/lib/src/services/resource/checkout/payments.js:28:45)
  at new Checkout (node_modules/@adyen/api-library/lib/src/services/checkout.js:43:26)
  at new AdyenServerApi (node_modules/nuxt-adyen-module/dist/module.js:72:21)
  at createMiddleware (node_modules/nuxt-adyen-module/dist/module.js:230:26)
  at ModuleContainer.nuxtModule (node_modules/nuxt-adyen-module/dist/module.js:317:30)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)
```

The adyen config is provided to `next.config.js` as per the docs.
```js
  modules: [
     'nuxt-adyen-module'
  ],
  adyen: {
    // ...
    checkoutEndpoint: process.env.ADYEN_CHECKOUT_ENDPOINT,
    // ...
  }
```
p.s same outcome with the other way as well
```js
  modules: [
     ['nuxt-adyen-module', {}]
  ],
```

The config seems to be correctly passed to https://github.com/Baroshem/nuxt-adyen-module/blob/a9f6eb6dc4c82d709f2c8471f23b01a6b07ad048/src/runtime/middleware.ts#L10

but is lost or at least the `checkoutEndpoint` when passed to the `@adyen/api-library` lib...

`@adyen/api-library` is 10.1.0... I see on your yarn.lock is 10.0.0 ( don't really know if something changed overthere!)

Since didn't had much time for debug had to hack the `@adyen/api-library/lib/src/config.js` file in order to continue as fast as possible 

```js
if (!this._checkoutEndpoint) {
      const message = "Please provide your unique live url prefix on the setEnvironment() call on the Client or provide checkoutEndpoint in your config object.";
      // throw new Error(message);
      this._checkoutEndpoint = "https://checkout-test.adyen.com"
}
```

After the hotfix above and trying to do a checkout, the ayden component is shown, i can select payment method (usually iDEAL), but upon submitting the payment this is thrown...

```sh
ERROR  Error: Invalid URL: undefined/v68/payments, error code: undefined                                                                                                                                                                         23:48:09


 ERROR  TypeError [ERR_INVALID_URL]: Invalid URL: undefined/v68/payments                                                                                                                                                                          23:48:09

  at AdyenServerApi.initiatePayment (node_modules/nuxt-adyen-module/dist/module.js:195:13)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async node_modules/nuxt-adyen-module/dist/module.js:245:20
``` 

### Possible Solution

N/A: No time to debug in detail, 

### Steps to reproduce

Example code on my github: https://github.com/bokjo/vue-storefront-demo

Essentially: 
- `vsf init vsf-demo-app`
- yarn add nuxt-adyen-module
- add the adyen module and config into nuxt.config.js
- reference the `AdyenCheckout` component  in the Checkout.vue page
- yarn build or yarn dev

### What version of nuxt-adyen-module are you using?

2.0.0

### What version of Node.js are you using?

14

### What browser (and version) are you using?

Chrome Version 96.0.4664.55 (Official Build) (x86_64)

### What operating system (and version) are you using?

macOs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Hi @bokjo 

Thanks for reporting this issue. I will take a look at it 🙂

**Comment by bokjo** [comment]
> Hi @bokjo
> 
> Thanks for reporting this issue. I will take a look at it 🙂

Hey @Baroshem,

Just took a deeper look, and found out the root cause!

I had `test` as value  for `environment` in the config, as per the documentation example

https://github.com/Baroshem/nuxt-adyen-module/blob/22df87fb7581b2195daa83693309ef50ee16660a/docs/content/en/basic-usage.md?plain=1#L23

The Environment type expects `'LIVE' | 'TEST'`.
```js
export type Environment = 'LIVE' | 'TEST';
```

There should be validation on the config side for this, and fix in the documentation as well.

p.s the `environment` key is actually missing from the opions docs: https://nuxt-adyen.vercel.app/options-reference

I'll create PR later this evening or tomorrow morning, since I need it for proper deployment and testing .
