### ISSUE TITLE
[Docs]: AdyenCheckout component wrong import and checkoutEndpoint example url

### ISSUE THREAD

**Issue by bokjo** [Baroshem/nuxt-adyen-module#23]
### `AdyenCheckout` component wrong import 

https://github.com/Baroshem/nuxt-adyen-module/blob/a9f6eb6dc4c82d709f2c8471f23b01a6b07ad048/docs/content/en/basic-usage.md?plain=1#L41

- should be `import AdyenCheckout from 'nuxt-adyen-module/dist/runtime/AdyenCheckout.vue';`

### `checkoutEndpoint ` example

https://github.com/Baroshem/nuxt-adyen-module/blob/a9f6eb6dc4c82d709f2c8471f23b01a6b07ad048/docs/content/en/basic-usage.md?plain=1#L18

https://github.com/Baroshem/nuxt-adyen-module/blob/a9f6eb6dc4c82d709f2c8471f23b01a6b07ad048/docs/content/en/options-reference.md?plain=1#L28

- `i.e. <http://localhost:8080/checkout>` should be something like `https://checkout-test.adyen.com` (depending on your env. [test or live]

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Hi @bokjo,

Thanks for raising this issue. I have added it to the 2.0.1 roadmap to fix in the upcoming new version release

**Comment by Baroshem** [comment]
Hi @bokjo 

Sorry for no contact from my side. I got sick for almost two weeks and was not able to get out of bed. I am taking a look at your PR's right now. Sorry for the delay.
